name: Flutter_Test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  flutter_test:
    runs-on: macos-latest
    if: ${{ !contains(github.event.pull_request.title, '[Skip CI]') }}
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.5'
    - run: flutter pub get
    - run: flutter test